---
#########################################
# Secret Variables defined in Gitlab:   #
#                                       #
# - SSH_DEPLOY_KEY                      #
# - DESTINATION_SERVER                  #
# - DESTINATION_DIRECTORY               #
#                                       #
#########################################
deploy:preprod:
  stage: deploy
  image: nixos/nix:2.3
  before_script:
    - nix-env -f '<nixpkgs>' -iA git openssh bash
    - ./deploy/pre_cd.sh
  script:
    - git remote add preprod "git@${DESTINATION_SERVER}:${DESTINATION_DIRECTORY}/${CI_PROJECT_NAME}.git"
    - git push --force preprod HEAD:master
    - cp ~/.ssh/known_hosts known_hosts
  cache:
    paths:
      - known_hosts
  only:
    - 9.0-lgds@lgds/foodcoops
