# Generated by Django 3.1.3 on 2020-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=300)),
                ('date_begin', models.DateTimeField(max_length=300)),
                ('date_end', models.DateTimeField(max_length=300)),
                ('icon', models.ImageField(upload_to='images/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
