# Generated by Django 3.1.4 on 2021-02-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=1)),
                ('picture', models.ImageField(default='images/default_icon.png', upload_to='images/users/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author_id', models.IntegerField(default=1)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=300)),
                ('date_begin', models.DateTimeField(max_length=300)),
                ('date_end', models.DateTimeField(max_length=300)),
                ('icon', models.ImageField(default='/images/default_icon.png', upload_to='images/')),
                ('image', models.ImageField(default='/images/default_image.png', upload_to='images/')),
                ('status', models.CharField(choices=[('ECV', 'En cours de validation'), ('VAL', 'Validé'), ('TER', 'Terminé')], default='ECV', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.adherent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
