# Generated by Django 3.1.3 on 2020-11-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.IntegerField(default=0),
        ),
    ]
