# Generated by Django 3.1.6 on 2021-04-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='odoo_id',
            field=models.IntegerField(default=0),
        ),
    ]
