# Generated by Django 3.1.3 on 2020-12-09 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adherant',
            new_name='Adherent',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='adherant',
            new_name='Adherent',
        ),
    ]
