# Generated by Django 3.1.3 on 2020-12-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201201_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.ImageField(default='/images/default_icon.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/images/default_image.png', upload_to='images/'),
        ),
    ]
