# Generated by Django 3.1.4 on 2021-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210206_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('ECV', 'En cours de validation'), ('VAL', 'Validé'), ('TER', 'Terminé')], default='ECV', max_length=20),
        ),
    ]
