# Generated by Django 3.1.3 on 2020-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_adherant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participation',
        ),
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.ManyToManyField(to='events.Adherant'),
        ),
    ]
