# Generated by Django 3.1.3 on 2020-12-01 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201201_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherant',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participation',
        ),
        migrations.AddField(
            model_name='adherant',
            name='picture',
            field=models.ImageField(default='images/default_icon.png', upload_to='images/users/'),
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.adherant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
